### ISSUE TITLE
Incomplete SettingsSchema binding

### ISSUE THREAD

**Issue by afranke** [gtk-rs/gio#120]
Fractal uses `Settings::list_schemas()` but `warning: use of deprecated item 'gio::Settings::list_schemas'` so I looked into replacing it. [The C docs](https://developer.gnome.org/gio/stable/GSettings.html#g-settings-list-schemas) tell me to use [`g_settings_schema_source_list_schemas()`](https://developer.gnome.org/gio/stable/gio-GSettingsSchema-GSettingsSchemaSource.html#g-settings-schema-source-list-schemas) but I couldn’t find it in [the Rust bindings](http://gtk-rs.org/docs/gio/struct.SettingsSchema.html).

**Comment by sdroege** [comment]
`GSettingsSchemaSource` is simply not bound yet, see `Gir.toml`.

**Comment by sdroege** [comment]
The documentation of that functions says `Do not call this function from normal programs. This is designed for use by database editors, commandline tools, etc.`

So maybe this is also not the way to go?

**Comment by sdroege** [comment]
Nonetheless, the bindings are added by this PR https://github.com/gtk-rs/gio/pull/121

**Comment by afranke** [comment]
> GSettingsSchemaSource is simply not bound yet, see Gir.toml.

Ha, I got mislead and missed the “Source” part of it. I guess that should have been part of #74 then.

> The documentation of that functions says Do not call this function from normal programs. This is designed for use by database editors, commandline tools, etc.
> 
> So maybe this is also not the way to go?

Damnit, you're right. What’s one supposed to do when something is deprecated but then they are told not to use the replacement? :-/

**Comment by afranke** [comment]
Thanks for the quick binding addition! I moved the discussion about Fractal’s code to #gnome-hackers and I’m going to use `lookup()` (which is part of the newly added binding, thanks again).
