### ISSUE TITLE
Idea for "magical" strings

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gio#174]
An idea that **could** (I don't think we should provide it into the bindings directly!) be implemented is as follows:

Currently we are using a wrapper to provide "magical" strings to gio (and in other places as well) such as:

```
add_action("app.quit", None)
```

Instead of `"app.quit"`, we could have for instance:

```
enum Kinds {
    App(Kind),
    System(kind),
    Nothing(Kind),
    // ...
}

enum Kind {
    Quit,
    // ...
}
```

And then we'd implement `ToString` and `FromString` for them. And to make their usage better/easier, we could change the `add_action` argument take `AsRef<str>` instead of `&str`.

I think it could be an interesting idea. Not sure what it'll evolve into... To be discussed! :)

**Comment by EPashkin** [comment]
IMHO is good idea to provide set of standard actions,
but at minimum "app.quit" is shorter that `Kinds::App(Kind::Quit)`,

**Comment by GuillaumeGomez** [comment]
It is, but less safe.

**Comment by sdroege** [comment]
In the bindings I would only provide string constants for those well-known action names. In applications you could build an enum out of them that can implement from/to string but the problem with having this in the bindings would be that it's not nicely extensible by the application-specific actions.

**Comment by EPashkin** [comment]
@sdroege There no problem with extensibility as action function still accept normal strings,
Ex. users can add enum for theirs operation and implement `AsRef<str>` for it.

**Comment by sdroege** [comment]
I've implemented something like this in https://github.com/sdroege/rustfest-rome18-gtk-gst-workshop/commit/a4a6cfd6fecd5485498a307991aefd6da8ca47cc

I don't think there's anything reasonable we can do here inside the bindings. The actions are completely app specific

**Comment by sdroege** [comment]
Closing then
