### ISSUE TITLE
How to convert Vec<GString> into Vec<String>

### ISSUE THREAD

**Issue by ignatenkobrain** [gtk-rs/gio#207]
Hello,

I have tried to port Fractal to use new gtk-rs, but I hit by the following problem.

```rust
// gio::ProxyResolver can't be sent or shared
thread_local! {
    static PROXY_RESOLVER: gio::ProxyResolver =
        gio::ProxyResolver::get_default().expect("Couldn't get proxy resolver");
}
[…]
let http_proxy = PROXY_RESOLVER.with(|resolver| resolver.lookup("http://", None))?;
```

and then passes to function which accepts `Vec<String>`. In latest gtk-rs release it changed to return `Vec<GString>`. So I have tried to do something like `.iter().map(|r| r.to_string())`, but I am getting something like:

```
error[E0283]: type annotations required: cannot resolve `_: glib::object::IsA<gio::auto::cancellable::Cancellable>`
```

And I can't get it done =(

Help is much appreciated.

**Comment by EPashkin** [comment]
This error from `None`, just use `NONE_CANCELLABLE`,
For conversion try:
`let v: Vec<String> = http_proxy.iter().map(std::convert::Into::into).collect();`
or it direct call as there From defined for String https://github.com/gtk-rs/glib/blob/master/src/gstring.rs#L199

**Comment by ignatenkobrain** [comment]
> This error from None, just use NONE_CANCELLABLE,

But that code does not have any cancellable. Is that new req in new gio?

**Comment by EPashkin** [comment]
Third parameter of lookup always was `Option<IsA<Cancelable>>` https://github.com/gtk-rs/gio/blob/master/src/auto/proxy_resolver.rs#L56

**Comment by ignatenkobrain** [comment]
Oh, got it.

Your suggestion with using `into()` did not work because compiler was not happy that it got `&GString` instead of `GString`. But `.to_string()` worked fine.

And your suggestion to use NONE_CANCELLABLE worked :)

Thanks! I am surprised that `None` does not work since it is `Option`, but whatever.

**Comment by EPashkin** [comment]
Before it was `Option<Cancelable>` then we understood that `Cancelable` can have children,
and change to `IsA<Cancelable>` broke usage of `None` without concrete type

Don't forget to close issue 😉

**Comment by ignatenkobrain** [comment]
Thanks for explanation!
