### ISSUE TITLE
Missing Permission::new()

### ISSUE THREAD

**Issue by mmstick** [gtk-rs/gio#214]
I'm not seeing a means of creating a `gio::Permission` to provide to a `gtk::LockButton`.

**Comment by GuillaumeGomez** [comment]
Maybe through http://gtk-rs.org/docs/gtk/trait.LockButtonExt.html#tymethod.get_permission?

**Comment by mmstick** [comment]
Seems we'll need [polkit bindings](https://www.freedesktop.org/software/polkit/docs/latest/PolkitPermission.html)

**Comment by sdroege** [comment]
`Permission` is an abstract class, you need subclasses of it for instantiation. For example `SimplePermission` here: http://gtk-rs.org/docs/gio/struct.SimplePermission.html#method.new

**Comment by sdroege** [comment]
But yes, you'd want polkit bindings. `SimplePermission` is mostly useless.

**Comment by sdroege** [comment]
Nothing to be done here, needs bindings for other libraries.
