### ISSUE TITLE
GIO is trying to list  g_desktop_app_info* on macos and causing link failure

### ISSUE THREAD

**Issue by samm-git** [gtk-rs/gio#272]
See https://github.com/gtk-rs/gir-files/issues/35 for the details. It needs to be conditionally disabled for macOS case.

**Comment by EPashkin** [comment]
@samm-git If you want do it yourself: DesktopAppInfo already have windows disable, seems only need update it. Format same as for `#[cfg`
https://github.com/gtk-rs/gio/blob/master/Gir.toml#L330
