### ISSUE TITLE
Add check to ensure that no manual_trait is forgotten

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gio#282]
We should put this check into an independent repository to be sure that we won't have to copy/paste it in all repositories every time.

What do you think @EPashkin @sdroege ?

**Comment by sdroege** [comment]
> We should put this check into an independent repository

The gir repository maybe? Also the check for the `assert_initialized!` macro calls should probably be moved there instead of copying it around everywhere.

**Comment by GuillaumeGomez** [comment]
No. Beyond the problem that I'd prefer having a centralized `check` repository or something along the line, the `gir` repository is referred to as a sub-repository. Therefore, if we update a check, we'd need to send a commit to all repository to update the reference, which I'd prefer to avoid if possible.

Also, I didn't understand what you wanted to say when talking about the `assert_initialized!` macro...

**Comment by EPashkin** [comment]
@GuillaumeGomez https://github.com/gtk-rs/gtk/blob/master/check_init_asserts has copy in all repos

**Comment by GuillaumeGomez** [comment]
Oh I see! Then definitely!

**Comment by GuillaumeGomez** [comment]
This can be closed now.
