### ISSUE TITLE
ApplicationExt::connect_handle_local_options() is missing

### ISSUE THREAD

**Issue by YaLTeR** [gtk-rs/gio#291]
For the [`handle-local-options` signal](https://developer.gnome.org/gio/stable/GApplication.html#GApplication-handle-local-options).

**Comment by sdroege** [comment]
The reason why it's not generated is because we have no bindings yet for `GVariantDict`.

**Comment by sdroege** [comment]
If you do a `Application` subclass you can do the same via the `handle_local_options` virtual method btw.

**Comment by YaLTeR** [comment]
I looked into it, but it seems that I cannot use GIO's option parsing machinery (`add_main_option`, etc.) if I do that then.

**Comment by sdroege** [comment]
Why not? That should work normally

**Comment by YaLTeR** [comment]
As far as I can see, the `handle_local_options` method accepts the raw command-line, and the actual parsing happens in GIO Application's implementation of that method. It parses the command-line into a `GVariantDict` and then passes it to the signal handler.

**Comment by sdroege** [comment]
`local_command_line` is called before, `handle_local_options` afterwards. That's the same as with the signals. But it seems we don't actually have `handle_local_options` there either, for the same reason.

**Comment by YaLTeR** [comment]
Oh, right, I was looking at `local_command_line`. Well, I guess it boils down to `GVariantDict` support.
