### ISSUE TITLE
Generate “open” signal for g_application

### ISSUE THREAD

**Issue by daa84** [gtk-rs/gio#31]
I try to generate https://developer.gnome.org/gio/stable/GApplication.html#GApplication-open
When add Gio.File, Gir generate next closure:
```rust
Fn(&P, &[File], i32, &str)
```
But looks like this is wrong, because as i understand `&[File]` array can't be generated properly without n_files field, so looks like it is need to write this code manually? To make proper conversion between array of pointers to rust slice? Or any other way exists?
Thanks

**Comment by GuillaumeGomez** [comment]
What is the `i32` for in here?

**Comment by daa84** [comment]
i32 is n_files - count of files in [File] array
as i understand **GFile is not finished with null value

**Comment by GuillaumeGomez** [comment]
Yes, that's my point. `n_files` is useless in Rust since it's supposed to be the length of the slice.

**Comment by daa84** [comment]
Ok, but how to implement this properly? Gir generator does not support such kind of thing? Does it need to implement this manually? Or maybe some converter already exists?

**Comment by GuillaumeGomez** [comment]
I wonder. I think we already did it but not sure if was in gir or manually...

cc @EPashkin

**Comment by EPashkin** [comment]
Yes, this need be manual. Something like this:
```rust
impl<O: IsA<Application> + IsA<glib::object::Object>> ApplicationExtManual for O {
   fn connect_open<F: Fn(&Self, &[File], &str) + 'static>(&self, f: F) -> u64 {
        unsafe {
            let f: Box_<Box_<Fn(&Self, &[File], &str) + 'static>> = Box_::new(Box_::new(f));
            connect(self.to_glib_none().0, "open",
                transmute(open_trampoline::<Self> as usize), Box_::into_raw(f) as *mut _)
        }
    }
}
unsafe extern "C" fn open_trampoline<P>(this: *mut ffi::GApplication, files: *const *mut ffi::GFile, n_files: libc::c_int, hint: *mut libc::c_char, f: glib_ffi::gpointer)
where P: IsA<Application> {
    callback_guard!();
    let f: &Box_<Fn(&P, &[File], &str) + 'static> = transmute(f);
    let files: Vec<File> = FromGlibPtrContainer::from_glib_none_num(files, n_files as usize);
    f(&Application::from_glib_none(this).downcast_unchecked(), &files[..], &String::from_glib_none(hint))
}
```

**Comment by daa84** [comment]
Thanks, i try 😄
