### ISSUE TITLE
How to use async reqwest HTTP client from gio event loop?

### ISSUE THREAD

**Issue by windelbouwman** [gtk-rs/gio#312]
I tried to fire an [async HTTP request using the reqwest crate](https://docs.rs/reqwest/0.10.7/reqwest/struct.Client.html) using the `context.spawn_local` trick.

This would throw me an error: `thread 'main' panicked at 'there is no timer running, must be called from the context of Tokio runtime'`.

Seems like the reqwest library expects a tokio event loop to be running, and not a gio one?

Any suggestions on how to approach this?

**Comment by sdroege** [comment]
reqwest only works on the tokio runtime (and none of the others), so you need to run one somewhere and spawn all tasks that needs tokio on that runtime. You could use e.g. the futures channels to communicate between that tokio runtime and others.

See the `tokio::runtime` module for information about how to run a tokio runtime.

On the gio runtime you should be able to use e.g. surf or isahc, or something like the http-types crate directly on the GIO socket connection.

**Comment by windelbouwman** [comment]
Would it be possible to run a tokio runtime onto the gio runtime?

**Comment by sdroege** [comment]
No, they can't be stacked but you have to run them separately and do communication between both parts explicitly via e.g. channels.
