### ISSUE TITLE
No TlsBackend?

### ISSUE THREAD

**Issue by chengchangwu** [gtk-rs/gio#323]
I'm porting the gstreamer's android initialization code to rust as [a learning project](https://github.com/chengchangwu/androidsink). The gstreamer-rs' appsink example works now. The only task left is `gst_android_load_gio_module`。For that I need the following four functions:

* `gst_android_load_gio_module`
* `g_tls_backend_get_default`
* `g_tls_file_database_new`
* `g_tls_backend_set_default_database`

I can find gio::TlsDatabase, gio::TlsFileDatabase, but no gio::TlsBackend. I think I should not use gio-sys directly. Could you suggest how I implement `gst_android_load_gio_module` or gio::TlsBackend in rust?

Followed is the code to be ported to rust:

```
void
gst_android_load_gio_modules (void)
{
  GTlsBackend *backend;
  const gchar *ca_certs;

  @G_IO_MODULES_LOAD@

  ca_certs = g_getenv ("CA_CERTIFICATES");

  backend = g_tls_backend_get_default ();
  if (backend && ca_certs) {
    GTlsDatabase *db;
    GError *error = NULL;

    db = g_tls_file_database_new (ca_certs, &error);
    if (db) {
      g_tls_backend_set_default_database (backend, db);
      g_object_unref (db);
    } else {
      g_warning ("Failed to create a database from file: %s",
          error ? error->message : "Unknown");
    }
  }
}
```

**Comment by sdroege** [comment]
`gio::TlsBackend` is not part of the `gio` bindings currently and would have to be added. Want to send a PR for that?

The alternative would be to use `gio-sys` and basically do what the C code is doing with some unsafe Rust code.

**Comment by chengchangwu** [comment]
Thanks. I do not understand TLS good enough yet to write a PR. I'll do with unsafe code.

**Comment by sdroege** [comment]
Ok, from what I can see this should be just a matter of adding `Gio.TlsBackend` to `Gir.toml` and then running `make`.

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs/pull/9

**Comment by chengchangwu** [comment]
Thank, I've thought that I could make a PR after I have studied gir, but your are fast;)
