### ISSUE TITLE
Simple way of calling `gio::ApplicationExt::run()` with `env::args()`?

### ISSUE THREAD

**Issue by jplatte** [gtk-rs/gio#42]
I have played around with this for some time, but didn't manage to come up with a nice way of calling `fn gio::ApplicationExt::run(&self, argv: &[&str]) -> i32` with `std::env::args()`. This is what I am doing at the moment, is there a better way?

```rust
let args = std::env::args(); // Iterator<Item = String>
let args_vec = args.collect::<Vec<_>>(); // Vec<String>
let args_ref_vec = args_vec.iter().map(|x| &x[..]).collect::<Vec<_>>(); // Vec<&str>

app.run(&args_ref_vec); // auto-deref to &[&str]
```

**Comment by GuillaumeGomez** [comment]
That's a good point.

**Comment by GuillaumeGomez** [comment]
@EPashkin: We should add a better way to do it. Something like this maybe:

```rust
fn run(&self, argv: ArgsOs) -> i32;
fn run(&self, argv: Args) -> i32;
```

**Comment by EPashkin** [comment]
With `Args` is better that current version. Not sure in what cases `ArgsOs` is needed (on Windows with Russian language `args()` works fine), so `run_os` IMHO unneeded.

**Comment by GuillaumeGomez** [comment]
Partially fixed in #56.

**Comment by sdroege** [comment]
What's left to be done here?

**Comment by sdroege** [comment]
Nothing I guess :)
