### ISSUE TITLE
Build of new SettingsSchemaKey API fails

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gio#67]
https://travis-ci.org/sdroege/gstreamer-rs/jobs/309075030#L1030-L1041

```
error[E0425]: cannot find function `g_settings_schema_key_ref` in module `ffi`

  --> /home/travis/.cargo/git/checkouts/gio-a4b825b310a073b9/c704556/src/auto/settings_schema_key.rs:17:27

   |

17 |         ref => |ptr| ffi::g_settings_schema_key_ref(ptr),

   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `g_settings_schema_ref`?

error[E0425]: cannot find function `g_settings_schema_key_unref` in module `ffi`

  --> /home/travis/.cargo/git/checkouts/gio-a4b825b310a073b9/c704556/src/auto/settings_schema_key.rs:18:29

   |

18 |         unref => |ptr| ffi::g_settings_schema_key_unref(ptr),

   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `g_settings_schema_unref`?

```

cc @EPashkin

**Comment by EPashkin** [comment]
You use feature `v2_40` ?

**Comment by sdroege** [comment]
`--all-features` actually (to make sure none of my features are conflicting with each other and they all always compile). It happens when using `gio` with `features = ["v2_38"]` or earlier. `v2_40` works fine as that will pull in the same feature from `gio-sys`.

The problem here is that the whole type is `v2_40`, but only its `impl` part is hidden behind that. The `glib_wrapper!` macro is not.

**Comment by GuillaumeGomez** [comment]
You're never supposed to run `--all-features`. Maybe we should add a check to see if more than one version feature is enabled at once to make the compilation fail (we now have a compilation_fail!` macro so wy not using it?).

**Comment by sdroege** [comment]
Why make something fail that generally works unless you break things?

Also again, this breaks also if you just enable a pre-2.40 feature on gio. This does not need --all-features to fail.

**Comment by EPashkin** [comment]
@sdroege Gio.SettingsSchemaKey don't have version in Gio-2.0.gir file,
so gir try detect it automatically by function, and some of function (g_settings_schema_key_get_description) have "2.34".
Can you try set version in config and check failure again.
Fix can be included in regen with https://github.com/gtk-rs/gir/pull/498

**Comment by sdroege** [comment]
You mean
```
[[object]]
name = "Gio.SettingsSchemaKey"
status = "generate"
version = "2.40"
```

That has no effect

**Comment by EPashkin** [comment]
Strange.
It don't change generated code?
`cargo build --all-features` on fixed gio works fine for me.
`cargo build --features="v2_34"` too.

**Comment by sdroege** [comment]
How does "fixed gio" look like? And yes, inside gio I also can't get it to fail for whatever reason. But create an empty new project with this in the Cargo.toml and it will fail: `gio = { git = "https://github.com/gtk-rs/gio", features = ["v2_38"] }`

**Comment by EPashkin** [comment]
Key changes is 
```diff
diff --git a/src/auto/mod.rs b/src/auto/mod.rs
index 8f4df03..fdf691c 100644
--- a/src/auto/mod.rs
+++ b/src/auto/mod.rs
@@ -1,4 +1,4 @@
-// This file was generated by gir (d50d839) from gir-files (469db10)
+// This file was generated by gir (83cd11e+) from gir-files (469db10)
 // DO NOT EDIT
 
 mod action;
@@ -101,9 +101,9 @@ pub use self::resource::Resource;
 mod settings_schema;
 pub use self::settings_schema::SettingsSchema;
 
-#[cfg(any(feature = "v2_34", feature = "dox"))]
+#[cfg(any(feature = "v2_40", feature = "dox"))]
 mod settings_schema_key;
-#[cfg(any(feature = "v2_34", feature = "dox"))]
+#[cfg(any(feature = "v2_40", feature = "dox"))]
 pub use self::settings_schema_key::SettingsSchemaKey;
```
Empty project with "v2_38" also builds fine for me.

**Comment by sdroege** [comment]
Yes that change would work

**Comment by EPashkin** [comment]
Strange that you don't get it generated by https://github.com/gtk-rs/gio/issues/67#issuecomment-348545925

**Comment by sdroege** [comment]
Well, let's merge this then and make my travis green again? :)

**Comment by EPashkin** [comment]
This? I don't see any PR for gio.

**Comment by sdroege** [comment]
I thought you submitted one :)

**Comment by EPashkin** [comment]
No, I still waiting your PR's with https://github.com/gtk-rs/gir/pull/498.
so I though that you can add this change to gio's.

**Comment by sdroege** [comment]
Not really important to do regens for that one, and as I wrote above the change in the .toml file does not work for me while it does for you. I must be adding something wrong to the .toml file.

**Comment by EPashkin** [comment]
IMHO any update that change many files in many crates better applied fast to simplify check future updates.
https://github.com/gtk-rs/gio/issues/67#issuecomment-348545925 is look right change for me,
may be you forgot to remove "Gio.SettingsSchemaKey" from `generate` array and gir just don't do anything.
