### ISSUE TITLE
Async tests stalls

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gio#93]
Sometimes gio test stalls
https://travis-ci.org/gtk-rs/gio/builds/348980232

Tried to add delay in spawned thread but it don't helps.

```diff
diff --git a/src/test_util.rs b/src/test_util.rs
index 660e6c0..40a7380 100644
--- a/src/test_util.rs
+++ b/src/test_util.rs
@@ -4,6 +4,7 @@
 
 
 use std::sync::mpsc::{channel, Sender};
+use std::time::Duration;
 use std::thread;
 use glib::*;
 
@@ -16,6 +17,7 @@ pub fn run_async<T: Send + 'static, Q: FnOnce(Sender<T>, MainLoop) + Send + 'sta
     let (tx, rx) = channel();
 
     thread::spawn(move || {
+        thread::sleep(Duration::from_millis(100));
         c.invoke(move || {
             start(tx, l_clone);
         });
```

**Comment by sdroege** [comment]
Do you have a backtrace of all threads when that happens?

**Comment by EPashkin** [comment]
It seems don't happened on my computer, only seen in travis.

**Comment by EPashkin** [comment]
Also not sure how get backtrace on stalling program.

**Comment by sdroege** [comment]
You could attach to it with `gdb --pid=12345`. But if this is only on travis then that's not going to work

**Comment by antoyo** [comment]
By the way, it's possible to run a travis build in debug mode and get a "ssh" access afterwards.
That might help to debug this issue.

**Comment by sdroege** [comment]
Fixed a long time ago
